//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultipleRoom
    {
        public int Id { get; set; }
        public int roomId { get; set; }
        public int reservationId { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Room Room { get; set; }
    }
}
