//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reciept
    {
        public int recieptId { get; set; }
        public int employeeId { get; set; }
        public int cutomerId { get; set; }
        public System.DateTime date { get; set; }
        public int reservationId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
